fatal: [dev]: FAILED! => {"msg": "The conditional check 'not (lookup('file', '{{ workdir }}/scripts/config.py').find(item.check) != -1)\n' failed. The error was: An unhandled exception occurred while running the lookup plugin 'file'. Error was a <class 'ansible.errors.AnsibleError'>, original message: could not locate file in lookup: /opt/test/099_test//scripts/config.py\n\nThe error appears to be in '/var/lib/jenkins/workspace/DataScience/test_models/099_model/deploy/ansible/roles/default/tasks/main.yaml': line 93, column 9, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n    block:\n      - name: ???????? ?????? {{ item }} ???? ?? ???\n        ^ here\nWe could be wrong, but this one looks like it might be an issue with\nmissing quotes. Always quote template expression brackets when they\nstart a value. For instance:\n\n    with_items:\n      - {{ foo }}\n\nShould be written as:\n\n    with_items:\n      - \"{{ foo }}\"\n"}
